# Volatility Alpha Thesis

## Core Concept

**Volatility Alpha** is the additional profit generated by capitalizing on price volatility through strategic buybacks during drawdowns, beyond the baseline profit from selling at all-time highs only.

## Two Synthetic Dividend Strategies

### 1. All-Time-High-Only Strategy (Baseline)
- **Primary Synthetic Dividends**: Sell small fractions only when price crosses previous all-time high
- **Predictable Cash Flow**: Total cash generated depends only on final price, not the path
- **Mathematical Certainty**: If price quadruples, you double your money + generate "bank" equal to initial investment
- **Timing Uncertainty**: Don't know *when* dividends arrive, only *how much*
- **Bull Market**: Multiple dividends per day possible
- **Drawdown**: Zero dividends until full recovery to new ATH

### 2. Volatility-Enhanced Strategy (ATH + Buybacks)
- **Primary Synthetic Dividends**: Same as baseline - sell at all-time highs
- **Secondary Synthetic Dividends**: Buy back sold shares during drawdowns, resell on recovery
- **"Rewinding the Clock"**: Buyback cancels the original sale, creating opportunity to resell
- **Repetition**: Process repeats in sideways/volatile markets
- **Mathematical Example**: 50% drawdown creates 8 rebalancing opportunities (2^(1/8) steps)
- **Gap Exploitation**: Overnight gaps create "free money" - buy lower, sell higher than expected
- **No Additional Risk**: Using capital from our own recent sales

## The Volatility Alpha Calculation

```
Volatility Alpha = (Enhanced Strategy Return) - (All-Time-High-Only Return)
```

### Mathematical Lower Bound

**Minimum Volatility Alpha Per Cycle** (October 2025 discovery):

For each buyback-resell cycle, the volatility alpha is approximately:

```
Alpha per cycle ≈ (trigger%)² / 2
```

**Derivation**: When you buy at price P, the stock drops by trigger% to P×(1-t), then rises back to P:
- Buy shares: cost = P×(1-t) per share
- Sell shares: revenue = P per share
- Profit = P - P×(1-t) = P×t
- Return on deployed capital ≈ t / (1-t) ≈ t + t²/2 for small t
- For small percentages, the t² term dominates: **Alpha ≈ t²/2**

**Example - SD8 (9.05% trigger)**:
```
Alpha per cycle ≈ 0.0905² / 2 ≈ 0.0041 = 0.41%

With 8 cycles per year:
Minimum annual alpha ≈ 8 × 0.41% ≈ 3.3%
```

**Example - SD16 (4.47% trigger)**:
```
Alpha per cycle ≈ 0.0447² / 2 ≈ 0.001 = 0.10%

With 16 cycles per year:
Minimum annual alpha ≈ 16 × 0.10% ≈ 1.6%
```

**Key Insights**:
1. **Count transactions = predict alpha**: Just inspect a stock chart and count buy opportunities to estimate minimum volatility alpha
2. **Linear relationship**: More cycles → more alpha (each cycle adds ~trigger²/2)
3. **Gaps are bonuses**: Price gaps up or down create extra profit beyond this minimum
4. **Small percentages compound**: With tiny percentages like 0.41%, addition ≈ compounding, so we can simply multiply by number of cycles

**The Beauty**: 
- The number of buyback cycles **directly controls** the lower limit of volatility alpha
- Market gaps and price discontinuities add **bonus alpha** on top of this minimum
- You can visually estimate potential alpha by counting drawdowns on a chart

**Real-World Validation**:
- GLD (low volatility): SD16, ~24 transactions → observed +0.72% alpha ✅
- NVDA (high volatility): SD6, many cycles → observed +7.53% alpha ✅

The formula provides a conservative lower bound. Actual alpha is typically higher due to:
- Overnight/intraday gaps
- Asymmetric price movements
- Multiple concurrent drawdown-recovery cycles

### Why It Exists

1. **Price Path Matters**: While ATH-only ignores the path, buybacks capitalize on it
2. **Drawdown Recycling**: Each drawdown creates multiple buy/sell opportunities
3. **Compounding Effect**: Profits from buyback-resell cycles compound over time
4. **Gap Arbitrage**: Market gaps create price inefficiencies we can exploit

### Frequency Parameter (sdN)

The "frequency" parameter determines how many rebalancing opportunities occur as price doubles:

- **sd4**: 4 rebalances per doubling → 18.9% trigger → High frequency, high volatility sensitivity
- **sd6**: 6 rebalances per doubling → 12.2% trigger → Moderate-high frequency
- **sd8**: 8 rebalances per doubling → 9.05% trigger → Moderate frequency
- **sd10**: 10 rebalances per doubling → 7.18% trigger → Lower frequency
- **sd12**: 12 rebalances per doubling → 5.95% trigger → Conservative frequency
- **sd16**: 16 rebalances per doubling → 4.43% trigger → Very conservative
- **sd20**: 20 rebalances per doubling → 3.53% trigger → Ultra-conservative

### Hypothesis

**Higher volatility assets benefit from lower sdN (higher frequency) because:**
- More price swings = more buyback opportunities
- Tighter triggers capture smaller volatility waves
- Each wave generates secondary synthetic dividends

**Lower volatility assets benefit from higher sdN (lower frequency) because:**
- Fewer price swings = fewer opportunities
- Wider triggers avoid whipsaws
- Transaction costs matter more with frequent rebalancing

## Evidence Required

To prove volatility alpha exists and is significant:

1. **Baseline Comparison**: Compare best sdN to all-time-high-only for same asset
2. **Volatility Alpha**: Calculate the difference in returns
3. **Statistical Significance**: Prove difference is not due to chance
4. **Consistency**: Show pattern holds across multiple assets
5. **Risk Assessment**: Verify no additional drawdown risk introduced

## Next Steps

1. Implement all-time-high-only backtest algorithm
2. Run comparison: best sdN vs ATH-only for all 12 assets
3. Calculate volatility alpha for each asset
4. Correlate volatility alpha with asset volatility
5. Publish findings with statistical tests

---

**Key Insight**: Volatility is traditionally seen as risk. Our thesis: **volatility is opportunity**. 
The synthetic dividend with buybacks transforms price volatility from risk into profit.
