-"-"-"-
-
-A-n-a-l-y-z-e- -t-h-e- -m-i-s-s-i-n-g- -o-p-p-o-r-t-u-n-i-t-y- -c-o-s-t- -o-n- -i-n-i-t-i-a-l- -c-a-p-i-t-a-l-.-
-
-
-
-T-h-i-s- -s-c-r-i-p-t- -q-u-a-n-t-i-f-i-e-s- -w-h-a-t- -w-e-'-r-e- -N-O-T- -c-u-r-r-e-n-t-l-y- -t-r-a-c-k-i-n-g-:- -t-h-e- -o-p-p-o-r-t-u-n-i-t-y- -c-o-s-t-
-
-o-n- -t-h-e- -i-n-i-t-i-a-l- -e-q-u-i-t-y- -p-o-s-i-t-i-o-n-.- -W-e- -t-r-a-c-k- -o-p-p-o-r-t-u-n-i-t-y- -c-o-s-t- -o-n- -n-e-g-a-t-i-v-e- -b-a-n-k-
-
-b-a-l-a-n-c-e- -d-u-r-i-n-g- -t-r-a-d-i-n-g-,- -b-u-t- -n-o-t- -o-n- -t-h-e- -$-1-0-0-k- -i-n-i-t-i-a-l- -c-a-p-i-t-a-l- -d-e-p-l-o-y-m-e-n-t-.-
-
-
-
-T-h-e- -a-n-a-l-y-s-i-s- -c-o-m-p-a-r-e-s-:-
-
--- -C-u-r-r-e-n-t- -m-e-t-r-i-c-s- -(-n-o- -i-n-i-t-i-a-l- -c-a-p-i-t-a-l- -o-p-p- -c-o-s-t-)-
-
--- -E-n-h-a-n-c-e-d- -m-e-t-r-i-c-s- -(-w-i-t-h- -i-n-i-t-i-a-l- -c-a-p-i-t-a-l- -o-p-p- -c-o-s-t-)-
-
--- -I-m-p-a-c-t- -o-n- -a-b-s-o-l-u-t-e- -r-e-t-u-r-n-s- -v-s- -v-o-l-a-t-i-l-i-t-y- -a-l-p-h-a-
-
-
-
-U-s-a-g-e-:-
-
- - - - -p-y-t-h-o-n- -s-r-c-/-r-e-s-e-a-r-c-h-/-i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-_-o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-.-p-y-
-
-"-"-"-
-
-
-
-i-m-p-o-r-t- -s-y-s-
-
-f-r-o-m- -p-a-t-h-l-i-b- -i-m-p-o-r-t- -P-a-t-h-
-
-f-r-o-m- -d-a-t-e-t-i-m-e- -i-m-p-o-r-t- -d-a-t-e-,- -t-i-m-e-d-e-l-t-a-
-
-f-r-o-m- -t-y-p-i-n-g- -i-m-p-o-r-t- -D-i-c-t-,- -A-n-y-,- -T-u-p-l-e-
-
-i-m-p-o-r-t- -p-a-n-d-a-s- -a-s- -p-d-
-
-i-m-p-o-r-t- -o-s-
-
-f-r-o-m- -c-o-n-t-e-x-t-l-i-b- -i-m-p-o-r-t- -r-e-d-i-r-e-c-t-_-s-t-d-o-u-t-
-
-
-
-#- -A-d-d- -p-r-o-j-e-c-t- -r-o-o-t- -t-o- -p-a-t-h-
-
-s-y-s-.-p-a-t-h-.-i-n-s-e-r-t-(-0-,- -s-t-r-(-P-a-t-h-(-_-_-f-i-l-e-_-_-)-.-p-a-r-e-n-t-.-p-a-r-e-n-t-.-p-a-r-e-n-t-)-)-
-
-
-
-f-r-o-m- -s-r-c-.-m-o-d-e-l-s-.-b-a-c-k-t-e-s-t- -i-m-p-o-r-t- -(-
-
- - - - -S-y-n-t-h-e-t-i-c-D-i-v-i-d-e-n-d-A-l-g-o-r-i-t-h-m-,-
-
- - - - -B-u-y-A-n-d-H-o-l-d-A-l-g-o-r-i-t-h-m-,-
-
- - - - -r-u-n-_-a-l-g-o-r-i-t-h-m-_-b-a-c-k-t-e-s-t-,-
-
-)-
-
-f-r-o-m- -s-r-c-.-d-a-t-a-.-f-e-t-c-h-e-r- -i-m-p-o-r-t- -H-i-s-t-o-r-y-F-e-t-c-h-e-r-
-
-
-
-
-
-d-e-f- -c-a-l-c-u-l-a-t-e-_-i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-_-o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-(-
-
- - - - -s-t-a-r-t-_-d-a-t-e-:- -d-a-t-e-,-
-
- - - - -e-n-d-_-d-a-t-e-:- -d-a-t-e-,-
-
- - - - -i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-:- -f-l-o-a-t-,-
-
- - - - -r-e-f-e-r-e-n-c-e-_-d-f-:- -p-d-.-D-a-t-a-F-r-a-m-e-,-
-
- - - - -r-e-f-e-r-e-n-c-e-_-t-i-c-k-e-r-:- -s-t-r- -=- -"-V-O-O-"-,-
-
-)- --->- -T-u-p-l-e-[-f-l-o-a-t-,- -f-l-o-a-t-]-:-
-
- - - - -"-"-"-
-
- - - - -C-a-l-c-u-l-a-t-e- -o-p-p-o-r-t-u-n-i-t-y- -c-o-s-t- -o-n- -i-n-i-t-i-a-l- -c-a-p-i-t-a-l- -o-v-e-r- -t-h-e- -b-a-c-k-t-e-s-t- -p-e-r-i-o-d-.-
-
- - - - -
-
- - - - -T-h-i-s- -i-s- -w-h-a-t- -w-e-'-r-e- -c-u-r-r-e-n-t-l-y- -N-O-T- -t-r-a-c-k-i-n-g- -b-u-t- -s-h-o-u-l-d- -b-e-.-
-
- - - - -
-
- - - - -A-r-g-s-:-
-
- - - - - - - - -s-t-a-r-t-_-d-a-t-e-:- -B-a-c-k-t-e-s-t- -s-t-a-r-t- -d-a-t-e-
-
- - - - - - - - -e-n-d-_-d-a-t-e-:- -B-a-c-k-t-e-s-t- -e-n-d- -d-a-t-e-
-
- - - - - - - - -i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-:- -I-n-i-t-i-a-l- -c-a-p-i-t-a-l- -d-e-p-l-o-y-e-d- -(-e-.-g-.-,- -$-1-0-0-,-0-0-0-)-
-
- - - - - - - - -r-e-f-e-r-e-n-c-e-_-d-f-:- -R-e-f-e-r-e-n-c-e- -a-s-s-e-t- -p-r-i-c-e- -d-a-t-a- -(-e-.-g-.-,- -V-O-O-)-
-
- - - - - - - - -r-e-f-e-r-e-n-c-e-_-t-i-c-k-e-r-:- -R-e-f-e-r-e-n-c-e- -a-s-s-e-t- -t-i-c-k-e-r- -n-a-m-e-
-
- - - - - - - - -
-
- - - - -R-e-t-u-r-n-s-:-
-
- - - - - - - - -T-u-p-l-e- -o-f- -(-o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-_-d-o-l-l-a-r-s-,- -o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-_-p-e-r-c-e-n-t-)-
-
- - - - -"-"-"-
-
- - - - -#- -N-o-r-m-a-l-i-z-e- -i-n-d-e-x-
-
- - - - -r-e-f-_-i-n-d-e-x-e-d- -=- -r-e-f-e-r-e-n-c-e-_-d-f-.-c-o-p-y-(-)-
-
- - - - -r-e-f-_-i-n-d-e-x-e-d-.-i-n-d-e-x- -=- -p-d-.-t-o-_-d-a-t-e-t-i-m-e-(-r-e-f-_-i-n-d-e-x-e-d-.-i-n-d-e-x-)-.-d-a-t-e-
-
- - - - -
-
- - - - -#- -F-i-n-d- -o-v-e-r-l-a-p-p-i-n-g- -d-a-t-e-s-
-
- - - - -d-a-t-e-s-_-i-n-_-r-a-n-g-e- -=- -[-d- -f-o-r- -d- -i-n- -r-e-f-_-i-n-d-e-x-e-d-.-i-n-d-e-x- -i-f- -s-t-a-r-t-_-d-a-t-e- -<-=- -d- -<-=- -e-n-d-_-d-a-t-e-]-
-
- - - - -
-
- - - - -i-f- -n-o-t- -d-a-t-e-s-_-i-n-_-r-a-n-g-e-:-
-
- - - - - - - - -r-e-t-u-r-n- -0-.-0-,- -0-.-0-
-
- - - - -
-
- - - - -#- -C-a-l-c-u-l-a-t-e- -d-a-i-l-y- -r-e-t-u-r-n-s-
-
- - - - -r-e-f-_-p-r-i-c-e-s- -=- -r-e-f-_-i-n-d-e-x-e-d-.-l-o-c-[-d-a-t-e-s-_-i-n-_-r-a-n-g-e-,- -'-C-l-o-s-e-'-]-.-a-s-t-y-p-e-(-f-l-o-a-t-)-
-
- - - - -d-a-i-l-y-_-r-e-t-u-r-n-s- -=- -r-e-f-_-p-r-i-c-e-s-.-p-c-t-_-c-h-a-n-g-e-(-)-.-f-i-l-l-n-a-(-0-.-0-)-
-
- - - - -
-
- - - - -#- -A-c-c-u-m-u-l-a-t-e- -o-p-p-o-r-t-u-n-i-t-y- -c-o-s-t- -o-n- -i-n-i-t-i-a-l- -c-a-p-i-t-a-l-
-
- - - - -o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-_-t-o-t-a-l- -=- -0-.-0-
-
- - - - -f-o-r- -d-a-i-l-y-_-r-e-t-u-r-n- -i-n- -d-a-i-l-y-_-r-e-t-u-r-n-s-.-v-a-l-u-e-s-:-
-
- - - - - - - - -o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-_-t-o-t-a-l- -+-=- -f-l-o-a-t-(-i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-)- -*- -f-l-o-a-t-(-d-a-i-l-y-_-r-e-t-u-r-n-)-
-
- - - - -
-
- - - - -o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-_-p-c-t- -=- -(-o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-_-t-o-t-a-l- -/- -i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-)- -*- -1-0-0-
-
- - - - -
-
- - - - -r-e-t-u-r-n- -o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-_-t-o-t-a-l-,- -o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-_-p-c-t-
-
-
-
-
-
-d-e-f- -a-n-a-l-y-z-e-_-b-a-c-k-t-e-s-t-_-w-i-t-h-_-f-u-l-l-_-o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-(-
-
- - - - -t-i-c-k-e-r-:- -s-t-r-,-
-
- - - - -s-t-a-r-t-_-d-a-t-e-:- -d-a-t-e-,-
-
- - - - -e-n-d-_-d-a-t-e-:- -d-a-t-e-,-
-
- - - - -i-n-i-t-i-a-l-_-q-t-y-:- -i-n-t-,-
-
- - - - -r-e-b-a-l-a-n-c-e-_-s-i-z-e-_-p-c-t-:- -f-l-o-a-t- -=- -9-.-0-5-,-
-
- - - - -p-r-o-f-i-t-_-s-h-a-r-i-n-g-_-p-c-t-:- -f-l-o-a-t- -=- -5-0-.-0-,-
-
- - - - -b-u-y-b-a-c-k-_-e-n-a-b-l-e-d-:- -b-o-o-l- -=- -T-r-u-e-,-
-
-)- --->- -D-i-c-t-[-s-t-r-,- -A-n-y-]-:-
-
- - - - -"-"-"-
-
- - - - -R-u-n- -b-a-c-k-t-e-s-t- -a-n-d- -c-a-l-c-u-l-a-t-e- -F-U-L-L- -o-p-p-o-r-t-u-n-i-t-y- -c-o-s-t- -(-c-u-r-r-e-n-t- -+- -m-i-s-s-i-n-g-)-.-
-
- - - - -
-
- - - - -A-r-g-s-:-
-
- - - - - - - - -t-i-c-k-e-r-:- -S-t-o-c-k- -t-o- -b-a-c-k-t-e-s-t-
-
- - - - - - - - -s-t-a-r-t-_-d-a-t-e-:- -B-a-c-k-t-e-s-t- -s-t-a-r-t-
-
- - - - - - - - -e-n-d-_-d-a-t-e-:- -B-a-c-k-t-e-s-t- -e-n-d-
-
- - - - - - - - -i-n-i-t-i-a-l-_-q-t-y-:- -I-n-i-t-i-a-l- -s-h-a-r-e-s-
-
- - - - - - - - -r-e-b-a-l-a-n-c-e-_-s-i-z-e-_-p-c-t-:- -R-e-b-a-l-a-n-c-e- -t-r-i-g-g-e-r- -t-h-r-e-s-h-o-l-d-
-
- - - - - - - - -p-r-o-f-i-t-_-s-h-a-r-i-n-g-_-p-c-t-:- -P-r-o-f-i-t- -s-h-a-r-i-n-g- -p-e-r-c-e-n-t-a-g-e-
-
- - - - - - - - -b-u-y-b-a-c-k-_-e-n-a-b-l-e-d-:- -W-h-e-t-h-e-r- -t-o- -e-n-a-b-l-e- -b-u-y-b-a-c-k-s-
-
- - - - - - - - -
-
- - - - -R-e-t-u-r-n-s-:-
-
- - - - - - - - -D-i-c-t- -w-i-t-h- -c-u-r-r-e-n-t- -m-e-t-r-i-c-s-,- -e-n-h-a-n-c-e-d- -m-e-t-r-i-c-s-,- -a-n-d- -c-o-m-p-a-r-i-s-o-n-
-
- - - - -"-"-"-
-
- - - - -p-r-i-n-t-(-f-"-\-n-{-'-=-'-*-7-0-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-A-n-a-l-y-z-i-n-g- -{-t-i-c-k-e-r-}-:- -{-s-t-a-r-t-_-d-a-t-e-}- -t-o- -{-e-n-d-_-d-a-t-e-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-I-n-i-t-i-a-l-:- -{-i-n-i-t-i-a-l-_-q-t-y-}- -s-h-a-r-e-s-"-)-
-
- - - - -p-r-i-n-t-(-f-"-{-'-=-'-*-7-0-}-\-n-"-)-
-
- - - - -
-
- - - - -#- -F-e-t-c-h- -d-a-t-a-
-
- - - - -f-e-t-c-h-e-r- -=- -H-i-s-t-o-r-y-F-e-t-c-h-e-r-(-)-
-
- - - - -d-f- -=- -f-e-t-c-h-e-r-.-g-e-t-_-h-i-s-t-o-r-y-(-t-i-c-k-e-r-,- -s-t-a-r-t-_-d-a-t-e-,- -e-n-d-_-d-a-t-e-)-
-
- - - - -v-o-o-_-d-f- -=- -f-e-t-c-h-e-r-.-g-e-t-_-h-i-s-t-o-r-y-(-"-V-O-O-"-,- -s-t-a-r-t-_-d-a-t-e-,- -e-n-d-_-d-a-t-e-)-
-
- - - - -
-
- - - - -i-f- -d-f-.-e-m-p-t-y- -o-r- -v-o-o-_-d-f-.-e-m-p-t-y-:-
-
- - - - - - - - -r-a-i-s-e- -V-a-l-u-e-E-r-r-o-r-(-f-"-F-a-i-l-e-d- -t-o- -f-e-t-c-h- -d-a-t-a- -f-o-r- -{-t-i-c-k-e-r-}- -o-r- -V-O-O-"-)-
-
- - - - -
-
- - - - -#- -G-e-t- -i-n-i-t-i-a-l- -p-r-i-c-e-
-
- - - - -d-f-_-i-n-d-e-x-e-d- -=- -d-f-.-c-o-p-y-(-)-
-
- - - - -d-f-_-i-n-d-e-x-e-d-.-i-n-d-e-x- -=- -p-d-.-t-o-_-d-a-t-e-t-i-m-e-(-d-f-_-i-n-d-e-x-e-d-.-i-n-d-e-x-)-.-d-a-t-e-
-
- - - - -f-i-r-s-t-_-d-a-t-e- -=- -m-i-n-(-d- -f-o-r- -d- -i-n- -d-f-_-i-n-d-e-x-e-d-.-i-n-d-e-x- -i-f- -d- ->-=- -s-t-a-r-t-_-d-a-t-e-)-
-
- - - - -i-n-i-t-i-a-l-_-p-r-i-c-e-_-s-e-r-i-e-s- -=- -d-f-_-i-n-d-e-x-e-d-.-l-o-c-[-f-i-r-s-t-_-d-a-t-e-,- -'-C-l-o-s-e-'-]-
-
- - - - -i-n-i-t-i-a-l-_-p-r-i-c-e- -=- -f-l-o-a-t-(-i-n-i-t-i-a-l-_-p-r-i-c-e-_-s-e-r-i-e-s-.-i-l-o-c-[-0-]-)- -i-f- -h-a-s-a-t-t-r-(-i-n-i-t-i-a-l-_-p-r-i-c-e-_-s-e-r-i-e-s-,- -'-i-l-o-c-'-)- -e-l-s-e- -f-l-o-a-t-(-i-n-i-t-i-a-l-_-p-r-i-c-e-_-s-e-r-i-e-s-)-
-
- - - - -i-n-i-t-i-a-l-_-c-a-p-i-t-a-l- -=- -i-n-i-t-i-a-l-_-q-t-y- -*- -i-n-i-t-i-a-l-_-p-r-i-c-e-
-
- - - - -
-
- - - - -p-r-i-n-t-(-f-"-I-n-i-t-i-a-l- -c-a-p-i-t-a-l-:- -{-i-n-i-t-i-a-l-_-q-t-y-}- -s-h-a-r-e-s- -�-�- -$-{-i-n-i-t-i-a-l-_-p-r-i-c-e-:-.-2-f-}- -=- -$-{-i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-:-,-.-2-f-}-\-n-"-)-
-
- - - - -
-
- - - - -#- -R-u-n- -a-l-g-o-r-i-t-h-m- -b-a-c-k-t-e-s-t- -(-s-u-p-p-r-e-s-s- -v-e-r-b-o-s-e- -o-u-t-p-u-t-)-
-
- - - - -w-i-t-h- -o-p-e-n-(-o-s-.-d-e-v-n-u-l-l-,- -'-w-'-)- -a-s- -d-e-v-n-u-l-l-:-
-
- - - - - - - - -w-i-t-h- -r-e-d-i-r-e-c-t-_-s-t-d-o-u-t-(-d-e-v-n-u-l-l-)-:-
-
- - - - - - - - - - - - -a-l-g-o- -=- -S-y-n-t-h-e-t-i-c-D-i-v-i-d-e-n-d-A-l-g-o-r-i-t-h-m-(-
-
- - - - - - - - - - - - - - - - -r-e-b-a-l-a-n-c-e-_-s-i-z-e-_-p-c-t-=-r-e-b-a-l-a-n-c-e-_-s-i-z-e-_-p-c-t-,-
-
- - - - - - - - - - - - - - - - -p-r-o-f-i-t-_-s-h-a-r-i-n-g-_-p-c-t-=-p-r-o-f-i-t-_-s-h-a-r-i-n-g-_-p-c-t-,-
-
- - - - - - - - - - - - - - - - -b-u-y-b-a-c-k-_-e-n-a-b-l-e-d-=-b-u-y-b-a-c-k-_-e-n-a-b-l-e-d-,-
-
- - - - - - - - - - - - -)-
-
- - - - - - - - - - - - -
-
- - - - - - - - - - - - -a-l-g-o-_-t-x-n-s-,- -a-l-g-o-_-s-u-m-m-a-r-y- -=- -r-u-n-_-a-l-g-o-r-i-t-h-m-_-b-a-c-k-t-e-s-t-(-
-
- - - - - - - - - - - - - - - - -d-f-=-d-f-,-
-
- - - - - - - - - - - - - - - - -t-i-c-k-e-r-=-t-i-c-k-e-r-,-
-
- - - - - - - - - - - - - - - - -i-n-i-t-i-a-l-_-q-t-y-=-i-n-i-t-i-a-l-_-q-t-y-,-
-
- - - - - - - - - - - - - - - - -s-t-a-r-t-_-d-a-t-e-=-s-t-a-r-t-_-d-a-t-e-,-
-
- - - - - - - - - - - - - - - - -e-n-d-_-d-a-t-e-=-e-n-d-_-d-a-t-e-,-
-
- - - - - - - - - - - - - - - - -a-l-g-o-=-a-l-g-o-,-
-
- - - - - - - - - - - - - - - - -r-e-f-e-r-e-n-c-e-_-a-s-s-e-t-_-d-f-=-v-o-o-_-d-f-,-
-
- - - - - - - - - - - - - - - - -r-e-f-e-r-e-n-c-e-_-a-s-s-e-t-_-t-i-c-k-e-r-=-"-V-O-O-"-,-
-
- - - - - - - - - - - - -)-
-
- - - - - - - - - - - - -
-
- - - - - - - - - - - - -#- -R-u-n- -b-u-y---a-n-d---h-o-l-d- -f-o-r- -c-o-m-p-a-r-i-s-o-n-
-
- - - - - - - - - - - - -b-h-_-a-l-g-o- -=- -B-u-y-A-n-d-H-o-l-d-A-l-g-o-r-i-t-h-m-(-)-
-
- - - - - - - - - - - - -b-h-_-t-x-n-s-,- -b-h-_-s-u-m-m-a-r-y- -=- -r-u-n-_-a-l-g-o-r-i-t-h-m-_-b-a-c-k-t-e-s-t-(-
-
- - - - - - - - - - - - - - - - -d-f-=-d-f-,-
-
- - - - - - - - - - - - - - - - -t-i-c-k-e-r-=-t-i-c-k-e-r-,-
-
- - - - - - - - - - - - - - - - -i-n-i-t-i-a-l-_-q-t-y-=-i-n-i-t-i-a-l-_-q-t-y-,-
-
- - - - - - - - - - - - - - - - -s-t-a-r-t-_-d-a-t-e-=-s-t-a-r-t-_-d-a-t-e-,-
-
- - - - - - - - - - - - - - - - -e-n-d-_-d-a-t-e-=-e-n-d-_-d-a-t-e-,-
-
- - - - - - - - - - - - - - - - -a-l-g-o-=-b-h-_-a-l-g-o-,-
-
- - - - - - - - - - - - - - - - -r-e-f-e-r-e-n-c-e-_-a-s-s-e-t-_-d-f-=-v-o-o-_-d-f-,-
-
- - - - - - - - - - - - - - - - -r-e-f-e-r-e-n-c-e-_-a-s-s-e-t-_-t-i-c-k-e-r-=-"-V-O-O-"-,-
-
- - - - - - - - - - - - -)-
-
- - - - -
-
- - - - -#- -C-a-l-c-u-l-a-t-e- -m-i-s-s-i-n-g- -o-p-p-o-r-t-u-n-i-t-y- -c-o-s-t- -o-n- -i-n-i-t-i-a-l- -c-a-p-i-t-a-l-
-
- - - - -i-n-i-t-i-a-l-_-o-p-p-_-c-o-s-t-_-d-o-l-l-a-r-s-,- -i-n-i-t-i-a-l-_-o-p-p-_-c-o-s-t-_-p-c-t- -=- -c-a-l-c-u-l-a-t-e-_-i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-_-o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-(-
-
- - - - - - - - -s-t-a-r-t-_-d-a-t-e-=-s-t-a-r-t-_-d-a-t-e-,-
-
- - - - - - - - -e-n-d-_-d-a-t-e-=-e-n-d-_-d-a-t-e-,-
-
- - - - - - - - -i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-=-i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-,-
-
- - - - - - - - -r-e-f-e-r-e-n-c-e-_-d-f-=-v-o-o-_-d-f-,-
-
- - - - -)-
-
- - - - -
-
- - - - -#- -B-u-i-l-d- -c-o-m-p-a-r-i-s-o-n-
-
- - - - -r-e-s-u-l-t- -=- -{-
-
- - - - - - - - -#- -B-a-c-k-t-e-s-t- -p-a-r-a-m-s-
-
- - - - - - - - -"-t-i-c-k-e-r-"-:- -t-i-c-k-e-r-,-
-
- - - - - - - - -"-s-t-a-r-t-_-d-a-t-e-"-:- -s-t-a-r-t-_-d-a-t-e-,-
-
- - - - - - - - -"-e-n-d-_-d-a-t-e-"-:- -e-n-d-_-d-a-t-e-,-
-
- - - - - - - - -"-i-n-i-t-i-a-l-_-q-t-y-"-:- -i-n-i-t-i-a-l-_-q-t-y-,-
-
- - - - - - - - -"-i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-"-:- -i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-,-
-
- - - - - - - - -
-
- - - - - - - - -#- -A-l-g-o-r-i-t-h-m- -r-e-s-u-l-t-s- -(-c-u-r-r-e-n-t- -r-e-p-o-r-t-i-n-g-)-
-
- - - - - - - - -"-a-l-g-o-_-n-a-m-e-"-:- -"-E-n-h-a-n-c-e-d-"- -i-f- -b-u-y-b-a-c-k-_-e-n-a-b-l-e-d- -e-l-s-e- -"-A-T-H---o-n-l-y-"-,-
-
- - - - - - - - -"-a-l-g-o-_-e-n-d-_-v-a-l-u-e-"-:- -a-l-g-o-_-s-u-m-m-a-r-y-[-'-e-n-d-_-v-a-l-u-e-'-]-,-
-
- - - - - - - - -"-a-l-g-o-_-h-o-l-d-i-n-g-s-"-:- -a-l-g-o-_-s-u-m-m-a-r-y-[-'-h-o-l-d-i-n-g-s-'-]-,-
-
- - - - - - - - -"-a-l-g-o-_-b-a-n-k-"-:- -a-l-g-o-_-s-u-m-m-a-r-y-[-'-b-a-n-k-'-]-,-
-
- - - - - - - - -"-a-l-g-o-_-t-o-t-a-l-"-:- -a-l-g-o-_-s-u-m-m-a-r-y-[-'-t-o-t-a-l-'-]-,-
-
- - - - - - - - -"-a-l-g-o-_-t-o-t-a-l-_-r-e-t-u-r-n-_-p-c-t-"-:- -a-l-g-o-_-s-u-m-m-a-r-y-[-'-t-o-t-a-l-_-r-e-t-u-r-n-'-]-,-
-
- - - - - - - - -
-
- - - - - - - - -#- -O-p-p-o-r-t-u-n-i-t-y- -c-o-s-t-s- -(-c-u-r-r-e-n-t- -t-r-a-c-k-i-n-g-)-
-
- - - - - - - - -"-c-u-r-r-e-n-t-_-o-p-p-_-c-o-s-t-_-t-r-a-d-i-n-g-"-:- -a-l-g-o-_-s-u-m-m-a-r-y-.-g-e-t-(-'-o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-'-,- -0-.-0-)-,-
-
- - - - - - - - -"-c-u-r-r-e-n-t-_-r-i-s-k-_-f-r-e-e-_-g-a-i-n-s-"-:- -a-l-g-o-_-s-u-m-m-a-r-y-.-g-e-t-(-'-r-i-s-k-_-f-r-e-e-_-g-a-i-n-s-'-,- -0-.-0-)-,-
-
- - - - - - - - -
-
- - - - - - - - -#- -M-i-s-s-i-n-g- -o-p-p-o-r-t-u-n-i-t-y- -c-o-s-t-
-
- - - - - - - - -"-m-i-s-s-i-n-g-_-o-p-p-_-c-o-s-t-_-i-n-i-t-i-a-l-_-d-o-l-l-a-r-s-"-:- -i-n-i-t-i-a-l-_-o-p-p-_-c-o-s-t-_-d-o-l-l-a-r-s-,-
-
- - - - - - - - -"-m-i-s-s-i-n-g-_-o-p-p-_-c-o-s-t-_-i-n-i-t-i-a-l-_-p-c-t-"-:- -i-n-i-t-i-a-l-_-o-p-p-_-c-o-s-t-_-p-c-t-,-
-
- - - - - - - - -
-
- - - - - - - - -#- -E-n-h-a-n-c-e-d- -m-e-t-r-i-c-s- -(-w-h-a-t- -w-e- -S-H-O-U-L-D- -r-e-p-o-r-t-)-
-
- - - - - - - - -"-e-n-h-a-n-c-e-d-_-t-o-t-a-l-_-o-p-p-_-c-o-s-t-"-:- -a-l-g-o-_-s-u-m-m-a-r-y-.-g-e-t-(-'-o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-'-,- -0-.-0-)- -+- -i-n-i-t-i-a-l-_-o-p-p-_-c-o-s-t-_-d-o-l-l-a-r-s-,-
-
- - - - - - - - -"-e-n-h-a-n-c-e-d-_-n-e-t-_-p-r-o-f-i-t-"-:- -a-l-g-o-_-s-u-m-m-a-r-y-[-'-t-o-t-a-l-'-]- --- -i-n-i-t-i-a-l-_-c-a-p-i-t-a-l- --- -(-a-l-g-o-_-s-u-m-m-a-r-y-.-g-e-t-(-'-o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-'-,- -0-.-0-)- -+- -i-n-i-t-i-a-l-_-o-p-p-_-c-o-s-t-_-d-o-l-l-a-r-s-)-,-
-
- - - - - - - - -"-e-n-h-a-n-c-e-d-_-n-e-t-_-r-e-t-u-r-n-_-p-c-t-"-:- -(-(-a-l-g-o-_-s-u-m-m-a-r-y-[-'-t-o-t-a-l-'-]- --- -i-n-i-t-i-a-l-_-c-a-p-i-t-a-l- --- -(-a-l-g-o-_-s-u-m-m-a-r-y-.-g-e-t-(-'-o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-'-,- -0-.-0-)- -+- -i-n-i-t-i-a-l-_-o-p-p-_-c-o-s-t-_-d-o-l-l-a-r-s-)-)- -/- -i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-)- -*- -1-0-0-,-
-
- - - - - - - - -
-
- - - - - - - - -#- -B-u-y---a-n-d---h-o-l-d- -c-o-m-p-a-r-i-s-o-n-
-
- - - - - - - - -"-b-h-_-t-o-t-a-l-_-r-e-t-u-r-n-_-p-c-t-"-:- -b-h-_-s-u-m-m-a-r-y-[-'-t-o-t-a-l-_-r-e-t-u-r-n-'-]-,-
-
- - - - - - - - -"-v-o-l-a-t-i-l-i-t-y-_-a-l-p-h-a-_-p-c-t-"-:- -a-l-g-o-_-s-u-m-m-a-r-y-[-'-t-o-t-a-l-_-r-e-t-u-r-n-'-]- --- -b-h-_-s-u-m-m-a-r-y-[-'-t-o-t-a-l-_-r-e-t-u-r-n-'-]-,-
-
- - - - - - - - -
-
- - - - - - - - -#- -N-u-m-b-e-r- -o-f- -t-r-a-n-s-a-c-t-i-o-n-s-
-
- - - - - - - - -"-n-u-m-_-t-r-a-n-s-a-c-t-i-o-n-s-"-:- -l-e-n-(-a-l-g-o-_-t-x-n-s-)- --- -1-,- - -#- -E-x-c-l-u-d-e- -i-n-i-t-i-a-l- -B-U-Y-
-
- - - - -}-
-
- - - - -
-
- - - - -r-e-t-u-r-n- -r-e-s-u-l-t-
-
-
-
-
-
-d-e-f- -p-r-i-n-t-_-a-n-a-l-y-s-i-s-_-r-e-s-u-l-t-s-(-r-e-s-u-l-t-:- -D-i-c-t-[-s-t-r-,- -A-n-y-]-)- --->- -N-o-n-e-:-
-
- - - - -"-"-"-P-r-i-n-t- -f-o-r-m-a-t-t-e-d- -a-n-a-l-y-s-i-s- -r-e-s-u-l-t-s-.-"-"-"-
-
- - - - -
-
- - - - -p-r-i-n-t-(-f-"-\-n-{-'-�-�-�-'-*-7-0-}-"-)-
-
- - - - -p-r-i-n-t-(-"-C-U-R-R-E-N-T- -R-E-P-O-R-T-I-N-G- -(-W-h-a-t- -W-e- -S-h-o-w- -T-o-d-a-y-)-"-)-
-
- - - - -p-r-i-n-t-(-f-"-{-'-�-�-�-'-*-7-0-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-S-t-r-a-t-e-g-y-:- -{-r-e-s-u-l-t-[-'-a-l-g-o-_-n-a-m-e-'-]-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-T-o-t-a-l- -R-e-t-u-r-n-:- -{-r-e-s-u-l-t-[-'-a-l-g-o-_-t-o-t-a-l-_-r-e-t-u-r-n-_-p-c-t-'-]-:-.-2-f-}-%-"-)-
-
- - - - -p-r-i-n-t-(-f-"- - -S-t-a-r-t- -V-a-l-u-e-:- -$-{-r-e-s-u-l-t-[-'-i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"- - -E-n-d- -V-a-l-u-e-:- - - -$-{-r-e-s-u-l-t-[-'-a-l-g-o-_-e-n-d-_-v-a-l-u-e-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"- - -P-r-o-f-i-t-:- - - - - - -$-{-r-e-s-u-l-t-[-'-a-l-g-o-_-e-n-d-_-v-a-l-u-e-'-]- --- -r-e-s-u-l-t-[-'-i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-\-n-F-i-n-a-l- -P-o-s-i-t-i-o-n-:-"-)-
-
- - - - -p-r-i-n-t-(-f-"- - -H-o-l-d-i-n-g-s-:- -{-r-e-s-u-l-t-[-'-a-l-g-o-_-h-o-l-d-i-n-g-s-'-]-:-,-}- -s-h-a-r-e-s-"-)-
-
- - - - -p-r-i-n-t-(-f-"- - -B-a-n-k-:- - - - - -$-{-r-e-s-u-l-t-[-'-a-l-g-o-_-b-a-n-k-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"- - -T-o-t-a-l-:- - - - -$-{-r-e-s-u-l-t-[-'-a-l-g-o-_-t-o-t-a-l-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-\-n-C-u-r-r-e-n-t- -O-p-p-o-r-t-u-n-i-t-y- -C-o-s-t- -T-r-a-c-k-i-n-g-:-"-)-
-
- - - - -p-r-i-n-t-(-f-"- - -F-r-o-m- -T-r-a-d-i-n-g- -(-n-e-g-a-t-i-v-e- -b-a-n-k-)-:- -$-{-r-e-s-u-l-t-[-'-c-u-r-r-e-n-t-_-o-p-p-_-c-o-s-t-_-t-r-a-d-i-n-g-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"- - -R-i-s-k---F-r-e-e- -G-a-i-n-s- -(-p-o-s-i-t-i-v-e- -b-a-n-k-)-:- -$-{-r-e-s-u-l-t-[-'-c-u-r-r-e-n-t-_-r-i-s-k-_-f-r-e-e-_-g-a-i-n-s-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"- - -N-e-t- -C-o-s-t-:- -$-{-r-e-s-u-l-t-[-'-c-u-r-r-e-n-t-_-o-p-p-_-c-o-s-t-_-t-r-a-d-i-n-g-'-]- --- -r-e-s-u-l-t-[-'-c-u-r-r-e-n-t-_-r-i-s-k-_-f-r-e-e-_-g-a-i-n-s-'-]-:-,-.-2-f-}-"-)-
-
- - - - -
-
- - - - -p-r-i-n-t-(-f-"-\-n-{-'-�-�-�-'-*-7-0-}-"-)-
-
- - - - -p-r-i-n-t-(-"-M-I-S-S-I-N-G- -O-P-P-O-R-T-U-N-I-T-Y- -C-O-S-T- -(-W-h-a-t- -W-e- -D-o-n-'-t- -T-r-a-c-k-)-"-)-
-
- - - - -p-r-i-n-t-(-f-"-{-'-�-�-�-'-*-7-0-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-I-n-i-t-i-a-l- -C-a-p-i-t-a-l- -D-e-p-l-o-y-e-d-:- -$-{-r-e-s-u-l-t-[-'-i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-V-O-O- -R-e-t-u-r-n- -O-v-e-r- -P-e-r-i-o-d-:- -{-r-e-s-u-l-t-[-'-m-i-s-s-i-n-g-_-o-p-p-_-c-o-s-t-_-i-n-i-t-i-a-l-_-p-c-t-'-]-:-.-2-f-}-%-"-)-
-
- - - - -p-r-i-n-t-(-f-"-O-p-p-o-r-t-u-n-i-t-y- -C-o-s-t- -o-n- -I-n-i-t-i-a-l- -C-a-p-i-t-a-l-:- -$-{-r-e-s-u-l-t-[-'-m-i-s-s-i-n-g-_-o-p-p-_-c-o-s-t-_-i-n-i-t-i-a-l-_-d-o-l-l-a-r-s-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-\-n-T-h-i-s- -i-s- -w-h-a-t- -w-e- -c-o-u-l-d- -h-a-v-e- -e-a-r-n-e-d- -i-f- -w-e- -i-n-v-e-s-t-e-d- -i-n- -V-O-O- -i-n-s-t-e-a-d-.-"-)-
-
- - - - -
-
- - - - -p-r-i-n-t-(-f-"-\-n-{-'-�-�-�-'-*-7-0-}-"-)-
-
- - - - -p-r-i-n-t-(-"-E-N-H-A-N-C-E-D- -R-E-P-O-R-T-I-N-G- -(-W-h-a-t- -W-e- -S-h-o-u-l-d- -S-h-o-w-)-"-)-
-
- - - - -p-r-i-n-t-(-f-"-{-'-�-�-�-'-*-7-0-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-G-r-o-s-s- -R-e-t-u-r-n-:- -{-r-e-s-u-l-t-[-'-a-l-g-o-_-t-o-t-a-l-_-r-e-t-u-r-n-_-p-c-t-'-]-:-.-2-f-}-%-"-)-
-
- - - - -p-r-i-n-t-(-f-"- - -E-n-d- -V-a-l-u-e- --- -S-t-a-r-t- -V-a-l-u-e-:- -$-{-r-e-s-u-l-t-[-'-a-l-g-o-_-e-n-d-_-v-a-l-u-e-'-]- --- -r-e-s-u-l-t-[-'-i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-\-n-T-o-t-a-l- -O-p-p-o-r-t-u-n-i-t-y- -C-o-s-t-:- -$-{-r-e-s-u-l-t-[-'-e-n-h-a-n-c-e-d-_-t-o-t-a-l-_-o-p-p-_-c-o-s-t-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"- - -F-r-o-m- -I-n-i-t-i-a-l- -C-a-p-i-t-a-l-:- -$-{-r-e-s-u-l-t-[-'-m-i-s-s-i-n-g-_-o-p-p-_-c-o-s-t-_-i-n-i-t-i-a-l-_-d-o-l-l-a-r-s-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"- - -F-r-o-m- -T-r-a-d-i-n-g-:- -$-{-r-e-s-u-l-t-[-'-c-u-r-r-e-n-t-_-o-p-p-_-c-o-s-t-_-t-r-a-d-i-n-g-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-\-n-N-e-t- -P-r-o-f-i-t- -A-f-t-e-r- -O-p-p-o-r-t-u-n-i-t-y- -C-o-s-t-:- -$-{-r-e-s-u-l-t-[-'-e-n-h-a-n-c-e-d-_-n-e-t-_-p-r-o-f-i-t-'-]-:-,-.-2-f-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-N-e-t- -R-e-t-u-r-n- -A-f-t-e-r- -O-p-p-o-r-t-u-n-i-t-y- -C-o-s-t-:- -{-r-e-s-u-l-t-[-'-e-n-h-a-n-c-e-d-_-n-e-t-_-r-e-t-u-r-n-_-p-c-t-'-]-:-.-2-f-}-%-"-)-
-
- - - - -
-
- - - - -p-r-i-n-t-(-f-"-\-n-{-'-�-�-�-'-*-7-0-}-"-)-
-
- - - - -p-r-i-n-t-(-"-V-O-L-A-T-I-L-I-T-Y- -A-L-P-H-A- -(-U-n-c-h-a-n-g-e-d- --- -T-h-i-s- -C-a-l-c-u-l-a-t-i-o-n- -I-s- -C-o-r-r-e-c-t-!-)-"-)-
-
- - - - -p-r-i-n-t-(-f-"-{-'-�-�-�-'-*-7-0-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-A-l-g-o-r-i-t-h-m- -R-e-t-u-r-n-:- -{-r-e-s-u-l-t-[-'-a-l-g-o-_-t-o-t-a-l-_-r-e-t-u-r-n-_-p-c-t-'-]-:-.-2-f-}-%-"-)-
-
- - - - -p-r-i-n-t-(-f-"-B-u-y---a-n-d---H-o-l-d- -R-e-t-u-r-n-:- -{-r-e-s-u-l-t-[-'-b-h-_-t-o-t-a-l-_-r-e-t-u-r-n-_-p-c-t-'-]-:-.-2-f-}-%-"-)-
-
- - - - -p-r-i-n-t-(-f-"-V-o-l-a-t-i-l-i-t-y- -A-l-p-h-a-:- -{-r-e-s-u-l-t-[-'-v-o-l-a-t-i-l-i-t-y-_-a-l-p-h-a-_-p-c-t-'-]-:-.-2-f-}-%-"-)-
-
- - - - -p-r-i-n-t-(-f-"-\-n-W-h-y- -u-n-c-h-a-n-g-e-d-?- -B-e-c-a-u-s-e- -b-o-t-h- -s-t-r-a-t-e-g-i-e-s- -p-a-y- -t-h-e- -s-a-m-e- -o-p-p-o-r-t-u-n-i-t-y- -c-o-s-t-"-)-
-
- - - - -p-r-i-n-t-(-f-"-o-n- -i-n-i-t-i-a-l- -c-a-p-i-t-a-l-,- -s-o- -i-t- -c-a-n-c-e-l-s- -o-u-t- -i-n- -t-h-e- -s-u-b-t-r-a-c-t-i-o-n-.-"-)-
-
- - - - -
-
- - - - -p-r-i-n-t-(-f-"-\-n-{-'-�-�-�-'-*-7-0-}-"-)-
-
- - - - -p-r-i-n-t-(-"-I-M-P-A-C-T- -S-U-M-M-A-R-Y-"-)-
-
- - - - -p-r-i-n-t-(-f-"-{-'-�-�-�-'-*-7-0-}-"-)-
-
- - - - -p-r-i-n-t-(-f-"-G-r-o-s-s- -r-e-t-u-r-n- -o-v-e-r-s-t-a-t-e-s- -n-e-t- -r-e-t-u-r-n- -b-y-:- -{-r-e-s-u-l-t-[-'-a-l-g-o-_-t-o-t-a-l-_-r-e-t-u-r-n-_-p-c-t-'-]- --- -r-e-s-u-l-t-[-'-e-n-h-a-n-c-e-d-_-n-e-t-_-r-e-t-u-r-n-_-p-c-t-'-]-:-.-2-f-}- -p-e-r-c-e-n-t-a-g-e- -p-o-i-n-t-s-"-)-
-
- - - - -p-r-i-n-t-(-f-"-M-i-s-s-i-n-g- -o-p-p-o-r-t-u-n-i-t-y- -c-o-s-t- -i-s-:- -{-(-r-e-s-u-l-t-[-'-m-i-s-s-i-n-g-_-o-p-p-_-c-o-s-t-_-i-n-i-t-i-a-l-_-d-o-l-l-a-r-s-'-]- -/- -r-e-s-u-l-t-[-'-i-n-i-t-i-a-l-_-c-a-p-i-t-a-l-'-]-)- -*- -1-0-0-:-.-2-f-}-%- -o-f- -i-n-i-t-i-a-l- -c-a-p-i-t-a-l-"-)-
-
- - - - -p-r-i-n-t-(-f-"-T-r-a-n-s-a-c-t-i-o-n-s- -e-x-e-c-u-t-e-d-:- -{-r-e-s-u-l-t-[-'-n-u-m-_-t-r-a-n-s-a-c-t-i-o-n-s-'-]-}-"-)-
-
-
-
-
-
-d-e-f- -m-a-i-n-(-)-:-
-
- - - - -"-"-"-R-u-n- -a-n-a-l-y-s-i-s- -o-n- -m-u-l-t-i-p-l-e- -s-c-e-n-a-r-i-o-s-.-"-"-"-
-
- - - - -
-
- - - - -p-r-i-n-t-(-"-\-n-"- -+- -"-=-"-*-7-0-)-
-
- - - - -p-r-i-n-t-(-"-I-N-I-T-I-A-L- -C-A-P-I-T-A-L- -O-P-P-O-R-T-U-N-I-T-Y- -C-O-S-T- -A-N-A-L-Y-S-I-S-"-)-
-
- - - - -p-r-i-n-t-(-"-Q-u-a-n-t-i-f-y-i-n-g- -W-h-a-t- -W-e-'-r-e- -N-O-T- -C-u-r-r-e-n-t-l-y- -T-r-a-c-k-i-n-g-"-)-
-
- - - - -p-r-i-n-t-(-"-=-"-*-7-0-)-
-
- - - - -
-
- - - - -s-c-e-n-a-r-i-o-s- -=- -[-
-
- - - - - - - - -{-
-
- - - - - - - - - - - - -"-n-a-m-e-"-:- -"-N-V-D-A- -E-n-h-a-n-c-e-d- -(-2-0-2-3---2-0-2-4-)-"-,-
-
- - - - - - - - - - - - -"-t-i-c-k-e-r-"-:- -"-N-V-D-A-"-,-
-
- - - - - - - - - - - - -"-s-t-a-r-t-_-d-a-t-e-"-:- -d-a-t-e-(-2-0-2-3-,- -1-,- -1-)-,-
-
- - - - - - - - - - - - -"-e-n-d-_-d-a-t-e-"-:- -d-a-t-e-(-2-0-2-4-,- -6-,- -3-0-)-,-
-
- - - - - - - - - - - - -"-i-n-i-t-i-a-l-_-q-t-y-"-:- -1-0-0-,-
-
- - - - - - - - - - - - -"-b-u-y-b-a-c-k-_-e-n-a-b-l-e-d-"-:- -T-r-u-e-,-
-
- - - - - - - - -}-,-
-
- - - - - - - - -{-
-
- - - - - - - - - - - - -"-n-a-m-e-"-:- -"-N-V-D-A- -A-T-H---o-n-l-y- -(-2-0-2-3---2-0-2-4-)-"-,-
-
- - - - - - - - - - - - -"-t-i-c-k-e-r-"-:- -"-N-V-D-A-"-,-
-
- - - - - - - - - - - - -"-s-t-a-r-t-_-d-a-t-e-"-:- -d-a-t-e-(-2-0-2-3-,- -1-,- -1-)-,-
-
- - - - - - - - - - - - -"-e-n-d-_-d-a-t-e-"-:- -d-a-t-e-(-2-0-2-4-,- -6-,- -3-0-)-,-
-
- - - - - - - - - - - - -"-i-n-i-t-i-a-l-_-q-t-y-"-:- -1-0-0-,-
-
- - - - - - - - - - - - -"-b-u-y-b-a-c-k-_-e-n-a-b-l-e-d-"-:- -F-a-l-s-e-,-
-
- - - - - - - - -}-,-
-
- - - - - - - - -{-
-
- - - - - - - - - - - - -"-n-a-m-e-"-:- -"-V-O-O- -E-n-h-a-n-c-e-d- -(-2-0-2-3---2-0-2-4-)-"-,-
-
- - - - - - - - - - - - -"-t-i-c-k-e-r-"-:- -"-V-O-O-"-,-
-
- - - - - - - - - - - - -"-s-t-a-r-t-_-d-a-t-e-"-:- -d-a-t-e-(-2-0-2-3-,- -1-,- -1-)-,-
-
- - - - - - - - - - - - -"-e-n-d-_-d-a-t-e-"-:- -d-a-t-e-(-2-0-2-4-,- -6-,- -3-0-)-,-
-
- - - - - - - - - - - - -"-i-n-i-t-i-a-l-_-q-t-y-"-:- -1-0-0-,-
-
- - - - - - - - - - - - -"-b-u-y-b-a-c-k-_-e-n-a-b-l-e-d-"-:- -T-r-u-e-,-
-
- - - - - - - - -}-,-
-
- - - - -]-
-
- - - - -
-
- - - - -r-e-s-u-l-t-s- -=- -[-]-
-
- - - - -
-
- - - - -f-o-r- -s-c-e-n-a-r-i-o- -i-n- -s-c-e-n-a-r-i-o-s-:-
-
- - - - - - - - -t-r-y-:-
-
- - - - - - - - - - - - -r-e-s-u-l-t- -=- -a-n-a-l-y-z-e-_-b-a-c-k-t-e-s-t-_-w-i-t-h-_-f-u-l-l-_-o-p-p-o-r-t-u-n-i-t-y-_-c-o-s-t-(-
-
- - - - - - - - - - - - - - - - -t-i-c-k-e-r-=-s-c-e-n-a-r-i-o-[-"-t-i-c-k-e-r-"-]-,-
-
- - - - - - - - - - - - - - - - -s-t-a-r-t-_-d-a-t-e-=-s-c-e-n-a-r-i-o-[-"-s-t-a-r-t-_-d-a-t-e-"-]-,-
-
- - - - - - - - - - - - - - - - -e-n-d-_-d-a-t-e-=-s-c-e-n-a-r-i-o-[-"-e-n-d-_-d-a-t-e-"-]-,-
-
- - - - - - - - - - - - - - - - -i-n-i-t-i-a-l-_-q-t-y-=-s-c-e-n-a-r-i-o-[-"-i-n-i-t-i-a-l-_-q-t-y-"-]-,-
-
- - - - - - - - - - - - - - - - -b-u-y-b-a-c-k-_-e-n-a-b-l-e-d-=-s-c-e-n-a-r-i-o-[-"-b-u-y-b-a-c-k-_-e-n-a-b-l-e-d-"-]-,-
-
- - - - - - - - - - - - -)-
-
- - - - - - - - - - - - -r-e-s-u-l-t-s-.-a-p-p-e-n-d-(-r-e-s-u-l-t-)-
-
- - - - - - - - - - - - -p-r-i-n-t-_-a-n-a-l-y-s-i-s-_-r-e-s-u-l-t-s-(-r-e-s-u-l-t-)-
-
- - - - - - - - - - - - -
-
- - - - - - - - -e-x-c-e-p-t- -E-x-c-e-p-t-i-o-n- -a-s- -e-:-
-
- - - - - - - - - - - - -i-m-p-o-r-t- -t-r-a-c-e-b-a-c-k-
-
- - - - - - - - - - - - -p-r-i-n-t-(-f-"-\-n-X-X- -F-a-i-l-e-d- -t-o- -a-n-a-l-y-z-e- -{-s-c-e-n-a-r-i-o-[-'-n-a-m-e-'-]-}-:-"-)-
-
- - - - - - - - - - - - -p-r-i-n-t-(-f-"- - - -E-r-r-o-r-:- -{-e-}-"-)-
-
- - - - - - - - - - - - -p-r-i-n-t-(-f-"-\-n- - - -T-r-a-c-e-b-a-c-k-:-"-)-
-
- - - - - - - - - - - - -t-r-a-c-e-b-a-c-k-.-p-r-i-n-t-_-e-x-c-(-)-
-
- - - - - - - - - - - - -c-o-n-t-i-n-u-e-
-
- - - - -
-
- - - - -#- -P-r-i-n-t- -s-u-m-m-a-r-y- -t-a-b-l-e-
-
- - - - -i-f- -r-e-s-u-l-t-s-:-
-
- - - - - - - - -p-r-i-n-t-(-f-"-\-n-{-'-=-'-*-7-0-}-"-)-
-
- - - - - - - - -p-r-i-n-t-(-"-C-O-M-P-A-R-I-S-O-N- -T-A-B-L-E-"-)-
-
- - - - - - - - -p-r-i-n-t-(-f-"-{-'-=-'-*-7-0-}-\-n-"-)-
-
- - - - - - - - -
-
- - - - - - - - -p-r-i-n-t-(-f-"-{-'-S-t-r-a-t-e-g-y-'-:-<-2-5-}- -{-'-G-r-o-s-s- -R-e-t-'-:-<-1-2-}- -{-'-O-p-p- -C-o-s-t-'-:-<-1-2-}- -{-'-N-e-t- -R-e-t-'-:-<-1-2-}- -{-'-V-o-l- -A-l-p-h-a-'-:-<-1-2-}-"-)-
-
- - - - - - - - -p-r-i-n-t-(-f-"-{-'---'-*-2-5-}- -{-'---'-*-1-2-}- -{-'---'-*-1-2-}- -{-'---'-*-1-2-}- -{-'---'-*-1-2-}-"-)-
-
- - - - - - - - -
-
- - - - - - - - -f-o-r- -r- -i-n- -r-e-s-u-l-t-s-:-
-
- - - - - - - - - - - - -s-t-r-a-t-e-g-y- -=- -f-"-{-r-[-'-t-i-c-k-e-r-'-]-}- -{-r-[-'-a-l-g-o-_-n-a-m-e-'-]-}-"-
-
- - - - - - - - - - - - -p-r-i-n-t-(-f-"-{-s-t-r-a-t-e-g-y-:-<-2-5-}- -"-
-
- - - - - - - - - - - - - - - - - - -f-"-{-r-[-'-a-l-g-o-_-t-o-t-a-l-_-r-e-t-u-r-n-_-p-c-t-'-]-:->-1-0-.-2-f-}-%- - -"-
-
- - - - - - - - - - - - - - - - - - -f-"-{-r-[-'-e-n-h-a-n-c-e-d-_-t-o-t-a-l-_-o-p-p-_-c-o-s-t-'-]-:->-1-0-,-.-0-f-}- - -"-
-
- - - - - - - - - - - - - - - - - - -f-"-{-r-[-'-e-n-h-a-n-c-e-d-_-n-e-t-_-r-e-t-u-r-n-_-p-c-t-'-]-:->-1-0-.-2-f-}-%- - -"-
-
- - - - - - - - - - - - - - - - - - -f-"-{-r-[-'-v-o-l-a-t-i-l-i-t-y-_-a-l-p-h-a-_-p-c-t-'-]-:->-1-0-.-2-f-}-%-"-)-
-
- - - - -
-
- - - - -p-r-i-n-t-(-f-"-\-n-{-'-=-'-*-7-0-}-"-)-
-
- - - - -p-r-i-n-t-(-"-A-n-a-l-y-s-i-s- -c-o-m-p-l-e-t-e-.- -S-e-e- -I-N-I-T-I-A-L-_-C-A-P-I-T-A-L-_-T-H-E-O-R-Y-.-m-d- -f-o-r- -i-m-p-l-e-m-e-n-t-a-t-i-o-n- -o-p-t-i-o-n-s-.-"-)-
-
- - - - -p-r-i-n-t-(-f-"-{-'-=-'-*-7-0-}-\-n-"-)-
-
-
-
-
-
-i-f- -_-_-n-a-m-e-_-_- -=-=- -"-_-_-m-a-i-n-_-_-"-:-
-
- - - - -m-a-i-n-(-)-
-
-
